### ISSUE TITLE
Failed to apply plugin 'android-buddy'.

### ISSUE THREAD

**Issue by 0113bernoyoun** [LikeTheSalad/android-buddy#8]
I'm trying to configure environment for using android-buddy. I found External Libraries has 'com.likethesalad.android:android-buddy-tools:1.1.1' but I got error when insert the [ id ' android-buddy']. Is it changed the method for configure the gradle?

below image : build.gradle(app)

![image](https://user-images.githubusercontent.com/35679738/175260903-e1c60e3c-8f00-4246-9aee-72d20d6fc185.png)
![image](https://user-images.githubusercontent.com/35679738/175260945-3bb64ba1-16d1-41d6-a36f-ce94e8ea2deb.png)
![image](https://user-images.githubusercontent.com/35679738/175260971-672a7dfa-511b-4e12-86c1-8f7423980966.png)

below image : build.gradle(project)
![image](https://user-images.githubusercontent.com/35679738/175261141-684e9bf0-2573-4946-aebc-5c3da7d58f60.png)

**Comment by LikeTheSalad** [comment]
Hi @0113bernoyoun

This is caused by recent changes in the way Gradle handles dependencies repositories: https://docs.gradle.org/7.4.2/userguide/dependency_management.html#sub:centralized-repository-declaration

I'm currently working on changes to avoid this issue, though in the meantime, you still can make it work by applying a couple of changes to your gradle files:

For the `settings.gradle` file, you should replace "RepositoriesMode.FAIL_ON_PROJECT_REPOS" by "RepositoriesMode.PREFER_PROJECT" like so:

```groovy
...
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_PROJECT)
    repositories {
    ...
}
```

And then, for your project's `build.gradle` file, you should add the following block to make sure you've got the repos needed for your dependencies:

```groovy
allprojects {
    repositories {
        mavenCentral()
        google()
    }
}
```

**Comment by resterdev** [comment]
Thank you for your kindness reply!

I fixed the problem when I apply to my app project.

But I'm in similiarity situation.

How can I cleary seperate android-buddy lib and app project?
build.gradle(app) in Library project(buddylib) can't plugin 'android-buddy'

I need to make android-buddy library project(a.k.a buddylib).
main app project use buddylib. 

I want to remove all android-buddy dependencies from main app project and only buddylib has android-buddy dependency.
But in your aaper repo, build.grdle(app) typed [apply plugin : 'android-buddy'] and build.gradle(project) has dependency [classpath "com.likethesalad.android:android-buddy-plugin:1.0.3"]


below image : library project build.gradle(app)
![image](https://user-images.githubusercontent.com/107384765/175871623-d6e51109-3a71-4b36-9a1e-2ab3b78bea36.png)
![image](https://user-images.githubusercontent.com/107384765/175871666-edbe4b03-250c-42cd-ae2f-36911aa9f4ec.png)

belwo code is my build.gradle
```

plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
//    id 'android-buddy'
    id 'android-buddy-library'
}

android {
    compileSdk 32

    defaultConfig {
        minSdk 22
        targetSdk 32
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }

    buildscript {
        repositories {
            mavenCentral()
        }
        dependencies {
            classpath 'com.android.tools.build:gradle:4.1.1'
            classpath 'com.likethesalad.android:android-buddy-tools:1.1.1'
            classpath "com.likethesalad.android:android-buddy-plugin:1.1.1"

        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'androidx.core:core-ktx:1.7.0'
    implementation 'androidx.appcompat:appcompat:1.4.2'
    implementation 'com.google.android.material:material:1.6.1'
    implementation 'com.likethesalad.android:android-buddy-tools:1.1.1'
    implementation 'com.likethesalad.android:android-buddy-plugin:1.0.3'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.3'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.4.0'
}

```

p.s 0113bernoyoun is my other account.

**Comment by LikeTheSalad** [comment]
Hi @resterdev, I see, though at the moment you need to define the "classpath" dependency in your build.gradle(project) file under buildscript.dependencies. That's the way Gradle used to get plugins before the new system was implemented. I'm working on changes to avoid this, but at the moment if you need to use the current versions, then you'd need to define the classpath in your project's build.gradle file.

**Comment by resterdev** [comment]
I understood. Thank you for your kind reply👍. I'm hoping for update.

**Comment by LikeTheSalad** [comment]
Hi! Just wanted to mention that now the [official Byte Buddy Gradle plugin](https://github.com/raphw/byte-buddy/tree/master/byte-buddy-gradle-plugin) has added support for Android projects! So this project is now deprecated and will no longer be maintained. Please go have a look at the [official plugin](https://github.com/raphw/byte-buddy/tree/master/byte-buddy-gradle-plugin) instead for instrumenting your Android projects. Thanks!
