### ISSUE TITLE
Change method to return your values

### ISSUE THREAD

**Issue by St4B** [LikeTheSalad/android-buddy#9]
How we could change the returned value of a function? 

Let's assume that we have the following class:

```kotlin
class Foo : Bar() {
	
    override fun barMethod(): Baz {
       return super.barMethod()
    }
}
```

What we want to do is to wrap the result and return the wrapper instead. Something like that:

```kotlin
class Foo : Bar() {
	
    override fun barMethod(): Baz {
        return BazDelegate(super.barMethod())
    }
}

class BazDelegate: Baz() {}
```

I 've created the interceptor, but the `originalMethodCall` as described in the example is a `Runnable`, which means that it does not return anything.
```kotlin
object MyInterceptor {

    @JvmStatic
    fun intercept(
        @SuperCall originalMethodCall: Runnable
    ) {
        originalMethodCall.run()
    }
}
```

**Comment by LikeTheSalad** [comment]
Hi @St4B - To reference a "SuperCall" you could either use a **Runnable**, as you're doing, or you could use a **Callable<RETURN_TYPE>** as well. The latter seems to be more useful for your case, so you'd need to define the originalMethodCall like so:

```kotlin
fun intercept(
    @SuperCall originalMethodCall: Callable<Baz>
) {...}
```

I hope it helps, though for more info on how to use the ByteBuddy API, I'd recommend checking the official docs: https://bytebuddy.net/#/tutorial

Cheers,
César
